# this is an example for how filesets can be defined in a repo config file
# so that they can be referenced in issue labels or manually in by the user.
filesets:
  - name: examples
    files:
      - examples/*.yaml
