kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: grafana.operate-first.cloud
  to:
    kind: Service
    name: grafana-service
  port:
    targetPort: 3000