apiVersion: v1
kind: Secret
metadata:
    name: aws-access-keys
type: Opaque
data:
    aws_access_key_id: ba3b9f8f-c9b7-4b5b-b8b7-f8f9f8f8f8f8
    aws_secret_access_key: 87ab23c5ef5190a
    aws_default_region: us-east-1
    aws_account: "123456789012"
