apiVersion: v1
kind: Secret
metadata:
    name: aws-access-keys
type: Opaque
data:
    aws_access_key_id: deadbeef12345678
    aws_secret_access_key: hunter2
    aws_default_region: us-east-1
    aws_account: "123456789012"
